# Generated by Django 3.2.6 on 2021-09-21 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210920_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='assigned_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_at', to='home.employee'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='belong_to', to='home.warehouse'),
        ),
    ]
