# Generated by Django 3.2.6 on 2021-09-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210920_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_necessary', models.BooleanField(default=False)),
                ('last_certification', models.DateTimeField()),
                ('certification_period', models.IntegerField(default=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certification', to='home.employee')),
            ],
        ),
    ]
