# Generated by Django 3.2.6 on 2021-10-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_certification_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='tool',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='certification', to='home.tool'),
        ),
    ]
