# Generated by Django 3.2.6 on 2022-02-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220208_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
